language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
script:
  - npm run build
deploy:
  provider: pages
  github_token: $github_token
  local_dir: build
  on:
    branch: master
  skip_cleanup: true
